import{a as C,S as I,i as g}from"./assets/vendor-6e0bf343.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function e(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(o){if(o.ep)return;o.ep=!0;const n=e(o);fetch(o.href,n)}})();const q="https://pixabay.com/api/",O="42600049-cf2a2f9bce39b2068dfff6d8c";async function p(t,r=1){try{return(await C.get(q,{params:{key:O,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}catch(e){throw console.error("Error fetching images:",e),e}}function y(t){return t.map(({webformatURL:r,largeImageURL:e,tags:c,likes:o,views:n,comments:a,downloads:S})=>`
      <li class='gallery-item'>
        <a class="gallery-link" href="${e}">
          <img class="gallery-image" src="${r}" alt="${c}" width="360"/>
        </a>
        <div class='image-info'>
          ${l(o,"Likes")}
          ${l(n,"Views")}
          ${l(a,"Comments")}
          ${l(S,"Downloads")}
        </div>
      </li>`).join("")}function l(t,r){return`
    <div class="info">
      <h3 class="info-label">${r}</h3>
      <p>${t}</p>
    </div>`}const b=new I(".gallery a",{captionsData:"alt",captionDelay:250}),m=document.querySelector(".form"),$=document.querySelector('input[name="search"]'),u=document.querySelector(".gallery"),L=document.querySelector(".loader"),h=document.querySelector(".js-load-btn");let f=1,s="";m.addEventListener("submit",t=>{if(t.preventDefault(),f=1,u.innerHTML="",s=$.value.trim(),console.log(s),s.length===0||s==="")i(),B();else{w();async function r(){try{const e=await p(s,f);return e.hits.length===0&&(i(),x()),console.log(e),e}catch(e){i(),console.log(e)}finally{d(),m.reset()}}r().then(e=>{console.log(e),u.innerHTML=y(e.hits),b.refresh(),e.hits.length>=15&&v()})}});h.addEventListener("click",P);async function P(){try{i(),w(),f+=1;const t=await p(s,f);u.insertAdjacentHTML("beforeend",y(t.hits)),b.refresh(),v(),k(),d(),t.hits.length<15&&(E(),i(),d())}catch{i()}}function k(){const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}function x(t){console.log(t),g.error({theme:"dark",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#ffffff",backgroundColor:"#ef4040",position:"topRight",pauseOnHover:!1,progressBarColor:"#b51b1b",timeout:3e3})}function B(){g.warning({message:"Please enter a search query",messageColor:"black",backgroundColor:"#ffac26",position:"topRight",pauseOnHover:!1,progressBarColor:"black",timeout:3e3})}function E(){g.info({maxWidth:"432px",messageSize:"16px",titleColor:" #fafafb",messageColor:"#fff",message:"We're sorry, but you've reached the end of search results.",closeOnEscape:!0,position:"topRight",backgroundColor:"#34c0eb"})}function v(){h.classList.remove("is-hidden")}function i(){h.classList.add("is-hidden")}function w(){L.style.display="block"}function d(){L.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
